
locals { timestamp = regex_replace(timestamp(), "[- TZ:]", "") }

variable "memory" {}

variable "cpus" {}

variable "iso_checksum" {}

variable "iso_url" {}

variable "guest_os_type" {}

variable "distro" {}

variable "release" {}

source "virtualbox-iso" "autogenerated-1" {
  boot_command         = ["<tab> text ks=http://{{ .HTTPIP }}:{{ .HTTPPort }}/ks.cfg<enter><wait>"]
  boot_wait            = "10s"
  disk_size            = 20000
  guest_additions_path = "VBoxGuestAdditions_{{.Version}}.iso"
  guest_os_type        = "${var.guest_os_type}"
  http_directory       = "http"
  iso_checksum         = "${var.iso_checksum}"
  iso_url              = "${var.iso_url}"
  shutdown_command     = "echo vagrant|sudo -S /sbin/shutdown -hP now"
  ssh_password         = "vagrant"
  ssh_port             = 22
  ssh_username         = "vagrant"
  ssh_wait_timeout     = "10000s"
  vboxmanage           = [["modifyvm", "{{.Name}}", "--memory", "${var.memory}"], ["modifyvm", "{{.Name}}", "--cpus", "${var.cpus}"]]
}


build {
  sources = ["source.virtualbox-iso.autogenerated-1"]
  provisioner "shell" {
    execute_command = "echo 'vagrant' | {{.Vars}} sudo -S  sh {{.Path}}"
    scripts = [
      "scripts/base.sh",
      "scripts/vagrant.sh",
      "scripts/virtualbox.sh",
      "scripts/provision.sh",
      "scripts/cleanup.sh",
      "scripts/zerodisk.sh"
    ]
  }

  post-processor "vagrant" {
    output = "${var.distro}-${var.release}-x64-virtualbox.box"
  }

}
