# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

ENV['distro']
ENV['version']
ENV['memory']
ENV['cpus']
ENV['ip_address']

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

config.vm.define "box" do |box|
    box.vm.box = "file://#{ENV['distro']}-#{ENV['version']}-x64-virtualbox.box"
    box.vm.network :private_network, ip: "#{ENV['ip_address']}"
    box.vm.hostname = "#{ENV['distro']}"
    box.ssh.insert_key = false
    
    box.vm.provider "virtualbox" do |v|
        v.customize [ "modifyvm", :id, "--cpus", "#{ENV['cpus']}" ]
        v.customize [ "modifyvm", :id, "--memory", "#{ENV['memory']}" ]
    end

end

 end
